server:
  port: 9003
spring:
  application:
    name: instant-notification
  cloud:
    stream:
      bindings:
        input:
          group: default
          destination: reduced-products
          durableSubscription: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: myTestMail@gmail.com
    password: myTestMailPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connecttimeout: 10000
          timeout: 10000
          writetimeout: 10000

  datasource:
    url: jdbc:mysql://localhost/price_monitor
    username: testuser
    password: testpass
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
