server:
  port: 9002
spring:
  application:
    name: price-monitor
  cloud:
    stream:
      bindings:
        input1:
          group: default
          destination: q_product_p1
          durableSubscription: true
        input2:
          group: default
          destination: q_product_p2
          durableSubscription: true
        input3:
          group: default
          destination: q_product_p3
          durableSubscription: true
        output1:
          destination: q_discount_product_p1
          durableSubscription: true
        output2:
          destination: q_discount_product_p2
          durableSubscription: true
        output3:
          destination: q_discount_product_p3
          durableSubscription: true

  datasource:
    url: jdbc:mysql://localhost/price_monitor
    username: testuser
    password: testpass
    driver-class-name: com.mysql.jdbc.Driver
  redis.host: localhost
  redis.port: 6379
  redis.pool.max-idle: 8
  redis.pool.min-idle: 0
  redis.pool.max-active: 8
  redis.pool.max-wait: -1

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

management:
  security:
    enabled: false