server:
  port: 9001
spring:
  application:
    name: product-crawler
  cloud:
    stream:
      bindings:
        output1:
          destination: q_product_p1
          durableSubscription: true
        output2:
          destination: q_product_p2
          durableSubscription: true
        output3:
          destination: q_product_p3
          durableSubscription: true
        log:
          destination: q_product_log
          durableSubscription: true

  datasource:
    url: jdbc:mysql://localhost/price_monitor
    username: testuser
    password: testpass
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

management:
  security:
    enabled: false